-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Jeu 11 Juin 2015 à 15:28
-- Version du serveur :  5.6.17
-- Version de PHP :  5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `proxifruit`
--

-- --------------------------------------------------------

--
-- Structure de la table `category`
--

CREATE TABLE IF NOT EXISTS `category` (
  `categoryName` varchar(45) NOT NULL,
  `ENUM('Fruit','Légume')` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`categoryName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `category`
--

INSERT INTO `category` (`categoryName`, `ENUM('Fruit','Légume')`) VALUES
('Fruit', 'Fruit'),
('Légume', 'légume');

-- --------------------------------------------------------

--
-- Structure de la table `comment`
--

CREATE TABLE IF NOT EXISTS `comment` (
  `idComment` int(11) NOT NULL AUTO_INCREMENT,
  `comment` varchar(255) DEFAULT NULL,
  `commentMark` int(11) DEFAULT NULL,
  `offer_numOffer` int(11) NOT NULL,
  `Member_idMember` int(11) NOT NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE KEY `offer_numOffer` (`offer_numOffer`),
  KEY `fk_comment_offer1_idx` (`offer_numOffer`),
  KEY `fk_Comment_Member1_idx` (`Member_idMember`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=11 ;

-- --------------------------------------------------------

--
-- Structure de la table `faq`
--

CREATE TABLE IF NOT EXISTS `faq` (
  `idFAQ` int(11) NOT NULL,
  `questions` varchar(255) DEFAULT NULL,
  `answers` text,
  PRIMARY KEY (`idFAQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Structure de la table `mailalert`
--

CREATE TABLE IF NOT EXISTS `mailalert` (
  `idmailAlert` int(11) NOT NULL AUTO_INCREMENT,
  `alertKeyWord` varchar(45) DEFAULT NULL,
  `Member_idMember` int(11) NOT NULL,
  PRIMARY KEY (`idmailAlert`),
  KEY `fk_mailAlert_Member1_idx` (`Member_idMember`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Structure de la table `member`
--

CREATE TABLE IF NOT EXISTS `member` (
  `idMember` int(11) NOT NULL AUTO_INCREMENT,
  `pseudo` varchar(45) NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `firstName` varchar(45) DEFAULT NULL,
  `picture` varchar(255) DEFAULT NULL,
  `phone` int(11) DEFAULT NULL,
  `pass` varchar(40) NOT NULL,
  `address` varchar(150) DEFAULT NULL,
  `cityPin` int(5) DEFAULT NULL,
  `city` varchar(40) DEFAULT NULL,
  `mail` varchar(45) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `memberType` int(11) DEFAULT NULL,
  `idPanier` int(11) NOT NULL,
  PRIMARY KEY (`idMember`),
  UNIQUE KEY `mail_UNIQUE` (`mail`),
  UNIQUE KEY `panier_idpanier_UNIQUE` (`idPanier`),
  UNIQUE KEY `Pseudo_UNIQUE` (`pseudo`),
  UNIQUE KEY `idMember_UNIQUE` (`idMember`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=22 ;

--
-- Contenu de la table `member`
--

INSERT INTO `member` (`idMember`, `pseudo`, `name`, `firstName`, `picture`, `phone`, `pass`, `address`, `cityPin`, `city`, `mail`, `description`, `memberType`, `idPanier`) VALUES
(1, 'Admin', NULL, NULL, 'upload/profil_admin.png', NULL, 'a4cbb2f3933c5016da7e83fd135ab8a48b67bf61', NULL, NULL, NULL, 'admin@isep.fr', NULL, 2, 0);

-- --------------------------------------------------------

--
-- Structure de la table `member_select_offer`
--

CREATE TABLE IF NOT EXISTS `member_select_offer` (
  `offer_numOffer` int(11) NOT NULL,
  `selectDate` datetime DEFAULT NULL,
  `Member_idMember` int(11) NOT NULL,
  PRIMARY KEY (`offer_numOffer`,`Member_idMember`),
  KEY `fk_member_has_offer_offer1_idx` (`offer_numOffer`),
  KEY `fk_member_select_offer_Member1_idx` (`Member_idMember`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Structure de la table `offer`
--

CREATE TABLE IF NOT EXISTS `offer` (
  `numOffer` int(11) NOT NULL AUTO_INCREMENT,
  `picture` varchar(45) DEFAULT NULL,
  `price` decimal(6,2) DEFAULT NULL,
  `priceType` varchar(3) DEFAULT NULL,
  `qty` tinyint(100) DEFAULT NULL,
  `qtyType` enum('kg','pièce(s)') DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `limitDate` datetime DEFAULT NULL,
  `offerDate` datetime DEFAULT NULL,
  `bio` varchar(10) DEFAULT NULL,
  `troc` varchar(10) DEFAULT NULL,
  `season` varchar(10) DEFAULT NULL,
  `Variety_idVariety` int(11) NOT NULL,
  `Member_idMember` int(11) NOT NULL,
  `distance` decimal(10,3) DEFAULT NULL,
  PRIMARY KEY (`numOffer`),
  KEY `fk_offer_Variety1_idx` (`Variety_idVariety`),
  KEY `fk_offer_Member1_idx` (`Member_idMember`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=22 ;

-- --------------------------------------------------------

--
-- Structure de la table `offer_has_panier`
--

CREATE TABLE IF NOT EXISTS `offer_has_panier` (
  `offer_numOffer` int(11) NOT NULL,
  `panier_idpanier` int(11) NOT NULL,
  `Member_idMember` int(11) NOT NULL,
  PRIMARY KEY (`offer_numOffer`,`panier_idpanier`),
  KEY `fk_offer_has_panier_offer1_idx` (`offer_numOffer`),
  KEY `fk_offer_has_panier_Member1_idx` (`Member_idMember`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Structure de la table `variety`
--

CREATE TABLE IF NOT EXISTS `variety` (
  `idVariety` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `category` enum('Fruit','Légume') DEFAULT NULL,
  `averageWeight` mediumint(9) DEFAULT NULL,
  `description` text,
  `picture` varchar(45) DEFAULT NULL,
  `Janvier` varchar(10) DEFAULT NULL,
  `Février` varchar(10) DEFAULT NULL,
  `Mars` varchar(10) DEFAULT NULL,
  `Avril` varchar(10) DEFAULT NULL,
  `Mai` varchar(10) DEFAULT NULL,
  `Juin` varchar(10) DEFAULT NULL,
  `Juillet` varchar(10) DEFAULT NULL,
  `Août` varchar(10) DEFAULT NULL,
  `Septembre` varchar(10) DEFAULT NULL,
  `Octobre` varchar(10) DEFAULT NULL,
  `Novembre` varchar(10) DEFAULT NULL,
  `Décembre` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`idVariety`),
  UNIQUE KEY `idVariety_UNIQUE` (`idVariety`),
  UNIQUE KEY `Name_UNIQUE` (`name`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=92 ;

--
-- Contenu de la table `variety`
--

INSERT INTO `variety` (`idVariety`, `name`, `category`, `averageWeight`, `description`, `picture`, `Janvier`, `Février`, `Mars`, `Avril`, `Mai`, `Juin`, `Juillet`, `Août`, `Septembre`, `Octobre`, `Novembre`, `Décembre`) VALUES
(1, 'Abricot', 'Fruit', 45, 'Plus ou moins gros selon les variétés, il conserve une teinte orangée caractéristique, souvent tachetée de rouge, et une peau duveteuse. Sa chair est pulpeuse, sucrée et juteuse.\r\nD’un apport calorique moyen, l’abricot est un des fruits les plus riches en provitamine A (ou carotène) : un fruit apporte pratiquement 50% du besoin quotidien. Croquez l’abricot à pleines dents pour profiter de cette source d’énergie gourmande.\r\nS’il est délicieux nature, l’abricot s’accommode aussi simplement en dessert, relevé de citron et/ou d’épices. Plus audacieux, il accompagne également les mets salés (canard, porc, viandes et poissons fumés, mâche, épinards).', './upload/abricot.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non'),
(2, 'Ail', 'Légume', 80, 'Une tête contient 10 à 12 gousses. Sa couleur couvre une palette allant du blanc au rose éclatant. Une fois épluchée, la gousse révèle une chair légèrement brillante et très parfumée.\r\nSa saveur relevée intègre facilement vos préparations salées pour un apport calorique limité.\r\nCru ou cuit, haché, en lamelles ou en chemise, l’ail se prête à de nombreuses déclinaisons gourmandes en relevant le goût de vos recettes.\r\nLa culture de l’ail se déroule au printemps et à l’automne. La France recense plusieurs variétés, dont certaines bénéficient d’un label de qualité.', './upload/ail.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui'),
(3, 'Airelle', 'Fruit', 1, 'Le fruit est une petite baie de couleur rouge ou bleue, de forme sphérique dont les graines sont noyées dans la pulpe. On peut les manger crues mais aussi cuites. C''est un fruit peu calorique et riche notamment en vitamines A et C et aussi en minéraux.', './upload/airelle.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non', 'non', 'non', 'non'),
(4, 'Amande', 'Fruit', 1, 'Le fruit est d’une belle couleur laiteuse et exhale un parfum délicat. Sa saveur est douce et légèrement sucrée.\r\nD’un apport énergétique élevé, l’amande est un fruit riche en lipides. Elle apporte également fibres et vitamine E, excellente pour le fonctionnement du système cardio-vasculaire.\r\nL’amande se consomme sous différentes formes : fraîche, effilée, en poudre, etc. Son goût se marie aussi bien aux recettes salées qu’aux desserts, auxquels elle apporte sa touche gourmande.\r\nL’amandier s’épanouit sous le climat bienveillant du sud de la France. Le verger local est encore restreint mais tend à se développer.\r\nCe fruit disponible toute l’année vous accompagne au quotidien pour vous donner tonus et énergie !', './upload/amande.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non', 'non'),
(5, 'Ananas', 'Fruit', 1800, 'Ce curieux fruit allongé couvert de motifs hexagonaux est surmonté d’une belle couronne de feuilles vertes et brillantes. La couleur de sa peau peut aller du vert à l’ocre, en passant par le rose. Sous cette écorce épaisse, la chair jaune dorée possède une saveur douce.\r\nSur les étals toute l’année, l’ananas est très riche en vitamine C, indispensable pour le tonus. Et même s’il paraît très sucré, son apport énergétique est limité, permettant d’en faire un allié forme au quotidien !\r\nFacile à marier, sa saveur s’intègre à de nombreuses recettes salées comme sucrées. Il est aussi délicieux nature avec sa chair parfumée et juteuse.\r\nIl faut compter 2 années de culture avant de récolter l’ananas.\r\nLongtemps considéré comme un fruit exotique rare, l’ananas a su se faire une place à la table des Français métropolitains.', './upload/ananas.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(6, 'Artichaut', 'Légume', 300, ' Ses feuilles denses se colorent de vert soutenu, de vert tendre ou d’un peu de violet.\r\nMoyennement énergétique, l’artichaut est gorgé de minéraux. Sa richesse en fer et en vitamine C en fait un bon atout antifatigue.\r\nL’artichaut se consomme presque toujours cuit, sauf certaines petites espèces violettes qui se dégustent relevées d’un peu de sauce.\r\nLes cultures d’artichauts se trouvent en Bretagne et dans le sud de la France, chacune de ces régions produisant des espèces différentes.', './upload/artichaut.jpg', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(7, 'Asperge', 'Légume', 50, 'Elle peut être blanche, violette ou verte, selon sa durée d’exposition au soleil. Son goût amer peut être plus ou moins prononcé.\r\nAvant de la consommer, vous devrez faire preuve d’un peu de patience et la cuire à la vapeur ou à l’eau. Vous pourrez ensuite la servir en entrée ou en garniture. Elle se marie, en effet, très bien avec les viandes.\r\nL’asperge est riche en potassium, en magnésium et en vitamines. Relativement peu calorique, vous pouvez la manger sans crainte.', './upload/asperge.jpg', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non'),
(8, 'Aubergine', 'Légume', 225, ' Sa couleur, sa taille et sa forme varient selon les variétés,. La plus fréquente sur les étals est l’aubergine violette, à la chair blanche et moelleuse.\r\nPauvre en calories, l’aubergine contient fibres, minéraux et vitamines en quantités importantes. Ce légume colore et vitamine vos plats tout l’été !\r\nL’aubergine est un légume facile à vivre qui se cuisine aisément. Sa chair fondante se marie à un grand nombre de préparations salées.\r\nL’aubergine est un des légumes emblématiques des beaux jours et de la cuisine méditerranéenne.', './upload/aubergine.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(9, 'Avocat', 'Fruit', 300, 'Sa peau noire, lisse ou rugueuse selon les variétés, révèle en son cœur une chair verte et onctueuse qui entoure un gros noyau.\r\nÉnergétique, l’avocat est un fruit riche en acides gras et en vitamines qui favorisent votre bien-être.\r\nL’avocat se consomme exclusivement cru. Il suffit de l’ouvrir en deux pour le savourer nature, relevé d’épices, d’herbes ou de citron, ou en accompagnement.\r\nDeux variétés d’avocat sont commercialisées en France, dont une petite partie est produite en Corse.', './upload/avocat.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(10, 'Banane', 'Fruit', 150, 'Recouverte d’une peau jaune devenant tigrée à maturité, elle possède une chair tendre et sucrée, très onctueuse.\r\nTrès équilibrée, la banane est un fruit riche en glucides, en fibres et en vitamines. Une banane par jour apporte une bonne dose d’énergie au quotidien.\r\nSi elle est délicieuse nature, la banane est aussi excellente revenue à la poêle, flambée ou encore cuisinée en gratin. Elle se marie très bien à des desserts gourmands et accompagne de manière surprenante certaines de vos préparations salées.\r\nLa banane dessert est la variété préférée des Français. Elle garnit les étals toute l’année, après avoir mûri au soleil des Antilles, de l’Afrique et de l’Amérique.', './upload/banane.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui'),
(11, 'Betterave', 'Légume', 300, ' Parente de la blette , la betterave rouge peut être aplatie, globuleuse ou allongée selon la variété.\r\nLa betterave, riche en sucre, est moyennement calorique. Sa consommation régulière est néanmoins recommandée, pour sa richesse en vitamines, minéraux et oligo-éléments essentiels.\r\nLa betterave est disponible toute l’année.\r\nLa betterave peut aussi bien être consommée crue, râpée, que cuite. Elle est alors délicieuse simplement cuite à l’eau ou au four, ou encore poêlée et relevée d’épices.', './upload/betterave.jpg', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(12, 'Blette', 'Légume', 200, 'Les deux variétés de blettes les plus commercialisées en France se reconnaissent à leur couleur : la blette blonde à carde blanche et la blette verte à carde blanche. Une fois cuite, sa chair est très fondante en bouche.\r\nLa blette est consommée exclusivement cuite, à la vapeur ou à la poêle. Sa chair prend alors une texture fondante en bouche et constitue un délicieux accompagnement.\r\nTrès pauvre en calories, la blette n’en est pas moins riche en vitamines et nutriments essentiels. Rapide à préparer et facile à accommoder, intégrez la blette dans votre alimentation au quotidien pour bénéficier de ses atouts nutritionnels.', './upload/blette.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(13, 'Brocoli', 'Légume', 275, ' Sa couleur verte provient du fait que ses bouquets sont exposés au soleil. Sa chair, qui peut être croquante ou fondante selon la cuisson, est douce et très typée.\r\nLe brocoli est un des légumes les plus denses en micronutriments (vitamines C et E notamment). Son apport en fibres en fait l’un des partenaires bien-être de votre assiette.\r\nC’est le légume facile à vivre par excellence. Il s’accommode très facilement au quotidien, que ce soit en soupe, en gratin, en beignet, en risotto, en tarte salée, en flan ou en terrine.\r\nLa culture du brocoli est essentiellement située en Bretagne, région dans laquelle il a été introduit dans les années 1980. Le climat doux et humide se révèle parfait pour assurer la croissance et la qualité de ce beau légume vert.', './upload/brocoli.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non'),
(14, 'Carambole', 'Fruit', 125, 'Ovoïde, ce fruit est reconnaissable entre tous grâce à ses côtes saillantes qui lui donnent, une fois découpé, une forme d’étoile.\r\nUn faible apport calorique allié à une grande richesse en vitamines font de la carambole un fruit qui apporte tonus et vitalité.\r\nLa carambole est le plus souvent utilisée comme élément décoratif. Elle est également goûteuse crue, en jus ou sous forme de compote ou de confiture.\r\nLes caramboles consommées en France proviennent d’Asie, d’Amérique et d’Israël.', './upload/carambole.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui'),
(15, 'Carotte', 'Légume', 125, 'Longtemps restée blanche et fibreuse, elle est aujourd’hui d’un beau rouge orangé et très savoureuse.\r\nEn cuisine, la carotte se décline sur toute la palette des textures et des saveurs. Cuite en gratin ou en purée, crue râpée ou taillée en bâtonnets, épicée, sucrée, glacée… avec elle, tout est possible !\r\nLa carotte est un vrai légume allié du bien-être, tant pour les enfants et que pour les adultes : une seule portion de 100 grammes couvre jusqu’à 200 % de nos besoins quotidiens en bêtacarotène ! Sans parler de ses nombreux minéraux.', './upload/carotte.jpg', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(16, 'Cassis', 'Fruit', 2, 'Sa peau lisse et brillante, allant du bleu profond au noir réglisse, recouvre une chair juteuse et acidulée.\r\nLe cassis allie un faible apport calorique et une grande richesse en vitamines. Croquer ses petites baies apporte bien-être et vitalité tout l’été.\r\nSi elle se croque nature, la baie de cassis révèle toute la richesse de sa saveur dans des nombreuses préparations gourmandes : confitures, tartes, gelées, mais aussi crème et liqueur.\r\nLa France cultive 2 variétés de cassis, concentrées principalement dans le Val de Loire, la Bourgogne, l’Oise et la Vallée du Rhône.\r\nLe cassis est un fruit d’été dont la saison est courte : à grignoter à l’envi aux beaux jours !', './upload/cassis.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non', 'non', 'non'),
(17, 'Céleri', 'Légume', 1000, 'Sa peau uniformément pâle recouvre une chair blanchâtre, croquante quand elle est consommée crue.\r\nPauvre en calories, le céleri-rave est un légume riche en vitamines, nutriments et oligoéléments. Pensez à le croquer ou à le cuisiner régulièrement pour intégrer tous ses bienfaits à vos menus.\r\nDélicieux râpé, croquant à souhait, le céleri-rave est également un régal poêlé, frit ou accommodé en soupe, gratin ou purée.', './upload/celeri.jpg', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(18, 'Cerise', 'Fruit', 15, 'Selon les variétés, sa peau est rouge (plus ou moins foncé), noire ou jaune orangée. sa chair est sucrée (90 % de la production française) ou acidulée.\r\nLes cerises sont souvent consommées telles quelles ou cuisinées en dessert : tartes, clafoutis, confiture, salades de fruit, etc. Mais vous pouvez également les préparer en garniture ou en sauce avec le canard, les gibiers, le porc et le veau. Vous pouvez aussi les intégrer à des crudités ou des salades.\r\nLes cerises sont un peu plus sucrées et caloriques que les autres fruits rouges. Toutefois, elles contiennent de nombreuses vitamines (B et C) ainsi que des minéraux.', './upload/cerise.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'non', 'non', 'non', 'non', 'non', 'non'),
(19, 'Champignon', 'Légume', 5, 'Sa peau est lisse et uniformément blanche ou blonde. Plus son chapeau est ouvert et plus il est concentré en goût.\r\nD’un apport calorique modéré, le champignon de Paris est un condensé de nutriments. Concentré en protéines et vitamines, c’est un aliment à inscrire régulièrement à vos menus.\r\nLe champignon de Paris est un allié de la cuisine au quotidien ou d’exception. Croquant cru, fondant cuit, facile à marier, il se déguste en soufflé, potage, purée, farci, sauté, cru, mijoté, etc.', './upload/champignon.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(20, 'Châtaigne', 'Fruit', 17, 'Sous la bogue recouverte de piquants, son enveloppe est d’un beau brun relevé de rouge brillant. Sa chair est farineuse et douce.\r\nD’un apport calorique élevé, la châtaigne est un fruit très riche en glucides. Il apporte également fibres et vitamines B9, idéales pour les muscles et le bien-être.\r\nLa châtaigne se prête à de nombreuses préparations gourmandes, poêlée, bouillie, en purée ou en potage.\r\nLa France compte de nombreuses châtaigneraies qui produisent des fruits goûteux. Plus de 700 espèces différentes ont été recensées par l’INRA.\r\nLa châtaigne est le fruit de l’automne par excellence.', './upload/chataigne.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'non', 'non'),
(21, 'Chicorée', 'Légume', 400, 'Sur les étals, les chicorées offrent une ribambelle de couleurs (rouge, vert, vert-jaune). Elles sont appréciées pour leur amertume.\r\nElles se dégustent à tous les moments du repas : en entrée, en plat, avec du fromage…\r\nLes chicorées présentent, par ailleurs, de sérieux atouts nutritionnels. Les chicorées frisées, par exemple, sont légères en calories mais renferment calcium et potassium.', './upload/chicoree.jpg', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(22, 'Chou', 'Légume', 2000, 'Vert, blanc ou rouge, le chou regroupe différentes variétés au feuillage lisse et dense ou aux larges feuilles vertes nervurées. Ce légume développe un goût typé en bouche.\r\nD’un apport énergétique faible, le chou est un légume très riche en vitamines. Il apporte également fibres, constituant ainsi un légume allié de votre bien-être.\r\nLe chou se consomme de différentes façons, associé à des plats rustiques et traditionnels aussi bien qu’à des préparations plus raffinées. Le plus souvent cuit à la vapeur, il est rapide et facile à préparer.', './upload/chou.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(23, 'Chou-fleur', 'Légume', 1500, 'Il est généralement blanc mais peut aussi être vert, violet ou orange.\r\nLe chou-fleur se déguste cru ou cuit. En salade, en gratin, en flan, en beignet, etc., vous trouverez forcément une recette qui vous plaise !\r\nLe chou-fleur est l’un des légumes les moins caloriques. Par ailleurs, bien pourvu en vitamine C et en fibres, vous pouvez le consommer sans modération !', './upload/chou-fleur.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(24, 'Citron', 'Fruit', 120, 'Selon les variétés, sa peau revêt plusieurs nuances, du jaune vif au jaune doré. Sa chair juteuse offre un large panel de saveurs, allant du sucré à l’amer, en passant par l’acide.\r\nEn France, trois ou quatre variétés de citrons sont principalement commercialisées. Une partie provient de Côte-d''Azur et de Corse.\r\nEn assaisonnement ou en quartiers dans une salade, en jus rafraîchissant ou en limonade : il y a mille et une façons de se régaler du citron.\r\nRiche en vitamine C, son apport calorique est pratiquement négligeable. Sa concentration en nutriments est une bonne raison supplémentaire de le déguster au quotidien !\r\nLe citron est disponible tout au long de l''année.\r\nUn citron vert pèse en moyenne 100 g. Plus petit et plus trapu que le citron jaune, son écorce se colore à maturité d''un joli vert brillant. Tendre, acide et très juteuse, sa pulpe possède un arôme caractéristique. Sa peau est lisse, mince, parfois coriace et adhérente.\r\nLe citron vert est très utile en cuisine. Recherché pour son jus et sa pulpe, il apporte fraîcheur et exotisme.', './upload/citron.jpg', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', '', 'oui'),
(25, 'Clémentine', 'Fruit', 35, 'En fonction de la variété, le fruit est plus ou moins gros. À maturité, sa peau rugueuse varie du vert à l’orange vif. Son goût doux et acidulé excite les papilles.\r\nLégère en calories mais riche en vitamine C, la clémentine est le fruit de l’énergie pendant les saisons froides.\r\nSon absence de pépins et sa chair plus juteuse lui a permis de supplanter la mandarine dans le cœur des Français.\r\nFacile à transporter, elle se déguste à toute heure de la journée. Elle réveille plats (viandes, salades, crustacés, poissons, féculents) et desserts de sa petite touche fraîcheur surprenante.\r\nLa Corse est le terroir de prédilection de la clémentine en France. Son climat généreux donne aux fruits toute leur saveur.', './upload/clementine.jpg', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui'),
(26, 'Coing', 'Fruit', 250, 'Fruit volumineux doté d''une belle couleur jaune serin, il possède à maturité un délicat petit duvet. De saveur acidulée, sa chair exhale un doux parfum qui vous rappellera peut-être quelques souvenirs d''enfance. \r\nSur les étals de France, vous rencontrerez principalement trois variétés de coings.\r\nLa présence de tanins confère des propriétés astringentes au coing, ainsi qu’une légère âcreté. Ainsi, le coing se consomme uniquement cuit, d’autant plus que sa chair est très dure.\r\nLe coing est peu chargé en glucides. En revanche, minéraux, oligo-éléments et vitamines y sont très présents, de même que les fibres.', './upload/coing.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'non', 'non'),
(27, 'Concombre', 'Légume', 400, 'En France, 80 % des concombres sont longs, droits et lisses. Leur chair verte est dépourvue d’amertume : elle est tendre et croquante, avec peu de graines au centre.\r\nLe concombre est habituellement consommé cru, mais il est également très savoureux servi cuit, en légume d''accompagnement. Pour cela, on le détaille en petits dés, que l''on cuit à la vapeur ou que l''on fait étuver doucement dans un peu de matière grasse.\r\nRiche en eau, le concombre est très désaltérant et peu calorique. Par ailleurs bien pourvu en vitamines et minéraux, c’est un allié incontournable de la forme au quotidien !', './upload/concombre.jpg', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non'),
(28, 'Courgette', 'Légume', 250, 'Sa peau brillante, d’un vert plus ou moins soutenu, parfois jaune doré, recèle une chair tendre, blanche à jaune pâle. La courgette varie en  longueur et en rondeur selon les variétés.\r\nLa courgette marie un apport calorique minimal et une concentration en vitamines et nutriments maximale. Riche en vitamines, elle accompagne et dynamise vos menus d’été et convient même aux tout-petits.\r\nFacile à vivre au quotidien, la courgette se consomme aussi bien cuite que crue, râpée, sautée, poêlée, farcie, etc. Sa préparation, de la découpe à la cuisson, est très rapide.\r\nLa culture de la courgette en France est récente. Originaire du Mexique, elle ne pousse sous nos latitudes que depuis le XIXe siècle. La courgette est un fruit consommée en tant que légume !', './upload/courgette.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(29, 'Cresson', 'Légume', 200, 'Cette belle salade d’exception, aux petites feuilles vertes, possède en bouche une saveur fine et légèrement poivrée. Sa texture fondante et croquante séduit les amateurs.\r\nD’un apport calorique minime, le cresson est un des légumes les plus riches en fer. Combiné à sa richesse en vitamines, cet atout en fait une salade délicate à consommer régulièrement.\r\nLe cresson est délicieux en salade, simplement relevé d’huile et de vinaigre parfumés, mais aussi en sauce crémée, en potage ou en purée.', './upload/cresson.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(30, 'Datte', 'Fruit', 10, 'En fonction des variétés, la forme de la datte varie et sa chair se fait plus ou moins moelleuse, mais reste toujours pleine de goût. La peau de la datte est ambrée et parfois translucide.\r\nLes dattes fraîches sont cueillies dès leur maturité et sont commercialisées encore attachées à la branche. Surtout consommées dans les pays producteurs, elles sont encore peu présentes sur les marchés français.\r\nLes dattes séchées ont commencé à se déshydrater sur l''arbre. Les fruits sains sont cueillis avec leur branche.\r\nLes dattes extra-sèches sont idéales pour le grignotage ou pour une pause gourmande et énergétique à tout moment de la journée.\r\nFraîche ou séchée, hachée, farcie ou en pâte de fruit, la datte se prête à toutes les préparations culinaires. Laissez libre cours à votre imagination.', './upload/datte.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(31, 'Echalote', 'Légume', 25, 'Sous sa fine peau noisette se cache une chair très odorante, légèrement piquante sur la langue et très aromatique.\r\nTraditionnellement très présente dans les habitudes alimentaires des Français, l’échalote régale au quotidien de ses bienfaits grâce aux vitamines et minéraux qu’elle contient.\r\nL’échalote est l’un des ingrédients aromatiques essentiels en cuisine. Disponible toute l’année, elle est délicieuse en fond de sauce ou dans les plats mijotés, mais aussi crue, finement ciselée sur une salade.\r\nL’échalote est un des condiments préférés des Français. De la même famille que l’oignon, elle est principalement cultivée en Bretagne et dans le Val-de-Loire.', './upload/echalote.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(32, 'Endive', 'Légume', 150, 'L’endive a été découverte par hasard au XIXe siècle. Issue de racines de chicorée sauvage améliorée, on ne la trouve pas à l’état naturel. Elle pousse sur des racines repiquées dans l’humidité, l’obscurité et la chaleur, c’est la technique du « forçage».\r\nLa France est de loin le premier producteur (et exportateur) européen, malgré une baisse progressive de la surface cultivée ces dernières années.\r\nBien que produit toute l’année, le chicon est considéré comme une salade d’hiver.\r\nTrès riche en eau et en fibres, l’endive contient également de nombreux minéraux et son apport en vitamine C n’est pas négligeable. Faites du chicon votre partenaire bien-être !\r\nCru et croquant, sa douceur s’associe à de nombreuses saveurs. Cuit à la vapeur, il présente une délicate amertume qui en fait un ingrédient de choix pour nombre de recettes, et pas seulement rustiques !', './upload/endive.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(33, 'Epinard', 'Légume', 1, 'L’épinard est une plante potagère dont on consomme les feuilles vertes.\r\nL’épinard pousse en quelques semaines seulement. Des variétés hybrides, plus résistantes ont progressivement supplanté les rustiques Géant d’hiver et Monstrueux de Viroflay…\r\nLa légende voudrait que l’épinard soit extrêmement riche en fer. La réalité est plus modérée, mais son apport en fibres et en vitamines est très intéressant.', './upload/epinard.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(34, 'Fenouil', 'Légume', 300, 'Son bulbe est blanc et côtelé. Il porte des tiges vert vif d’où se détache un feuillage dentelé.\r\nCousin très proche de l’anis, le fenouil a une saveur similaire et des propriétés semblables.\r\nC’est le parfum qui fait la différence dans nombre de plats mijotés !\r\nTrès faible en calories, bien pourvu en micronutriments… que demander de plus ?', './upload/fenouil.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui'),
(35, 'Fève', 'Légume', 5, 'Plus grosse graine de la grande famille des légumineuses, elle se cache dans une longue cosse aplatie. \r\nÀ la différence du haricot, elle possède une fine peau qu’il faut retirer avant de la croquer.\r\nÀ l’Épiphanie, elle se cache dans la galette des rois et symbolise une pièce de monnaie.\r\nLa fève présente un éventail de qualités nutritionnelles et un fort pouvoir de satiété : croquez-en si vous avez un petit creux et vous tiendrez facilement jusqu’au prochain repas.', './upload/feve.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non'),
(36, 'Figue', 'Fruit', 50, 'Selon les variétés, ses couleurs vont du vert au noir, en passant par le jaune et le rouge. La chair du fruit est onctueuse, et sa saveur douce, parfois acidulée.\r\nLa figue compte près de 750 variétés. On distingue les variétés remontantes - celles qui portent deux récoltes – de celles qui ne donnent qu''une fois l''an.\r\nDans l''assiette, la saveur de la figue vitamine vos préparations et s''associe très facilement avec les cuisines les plus simples comme les plus recherchées.\r\nSes fibres abondantes, sa forte teneur en calcium et sa modeste teneur en sucre sont autant de raisons de profiter d''elle à la maison, et de l''emmener au bureau pour une pause gourmande.', './upload/figue.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non'),
(37, 'Fraise', 'Fruit', 10, 'Selon les variétés, sa robe peut être rouge ou orangée et sa chair sucrée ou acidulée.\r\nPrincipalement consommée crue, la fraise peut également se prêter à des cuissons rapides à la poêle ou au four en papillote. Elle se cuisine volontiers, que ce soit en version sucrée ou en version salée. Tentez l’expérience, vous ne serez pas déçus !\r\nLa fraise est l’un des fruits qui contient le plus de vitamine C. À l’approche des beaux jours, elle prend ainsi le relais des agrumes pour recharger vos batteries. Comme tous les fruits rouges, elle est, par ailleurs, dotée d’un excellent pouvoir antioxydant. Peu calorique, vous pouvez en manger sans compter.', './upload/fraise.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non'),
(38, 'Framboise', 'Fruit', 4, 'Sur les étals, vous rencontrerez plusieurs variétés de framboises. Habituellement rouges, certaines peuvent être jaunes, orange, ambrées, noires - à ne pas confondre avec la mûre - ou blanches. La chair du fruit est sucrée, suave et acidulée.\r\n\r\nEn France, la framboise pousse encore à l''état sauvage dans certaines régions. La culture de ce fruit s''est développée dans les années 1950 durant lesquelles de nouvelles variétés – remontantes (permettant plusieurs récoltes annuelles) et plus robustes - ont été sélectionnées.\r\n\r\nCroquée nature au retour des courses ou utilisée dans une recette sophistiquée, la framboise a tous les atouts pour vous séduire !\r\nSon faible apport calorique en fait un fruit idéal pour les gourmands qui surveillent leur ligne. Elle contient par ailleurs des antioxydants, des fibres et des minéraux.', './upload/framboise.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(39, 'Fruit de la passion', 'Fruit', 75, 'Il pousse sur une liane, nommée passionaria. Selon la variété, le fruit de la passion peut être de couleur jaune, orangée ou brune.\r\n\r\nCe fruit exotique renferme une multitude de petites graines noires enrobées d''une pulpe translucide orangée et parfumée : l''arille.\r\n\r\nLa famille des passifloracées, à laquelle le fruit de la passion appartient, compte près de 400 espèces. Mais seules quelques-unes sont comestibles. Sur les étals français, la grenadille pourpre est l''espèce la plus répandue.\r\n\r\nFragile, le fruit de la passion supporte mal la cuisson mais se prête très bien à vos envies de créativité !\r\n\r\nLe fruit de la passion fournit du carotène, de la vitamine C, des minéraux et des fibres.', './upload/fruitdelapassion.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui'),
(40, 'Goyave', 'Fruit', 112, 'Lorsqu''elle mûrit, sa peau fine passe du vert pâle au jaune, et peut être piquetée de noir. Chez certaines variétés, la peau passe du rose au rouge. Sa chair juteuse et acidulée est de couleur crème à orange saumon, et elle est parsemée de petits grains durs.\r\nSur les étals de France, vous pourrez surtout trouver deux variétés distinctes : les goyaves en forme de poire et celles en forme de pomme.\r\nCrue et bien mûre, la goyave reste un fruit très facile à consommer : telle quelle, en jus, en sorbet, ou en sirop.\r\nD''un point de vue nutritif, ce fruit tropical présente un apport calorique très faible. Il est extrêmement riche en vitamine C et en fibres.', './upload/goyave.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui'),
(41, 'Grenade', 'Fruit', 325, ' Le fruit, en forme de pomme, d''abord vert, passe au rouge orangé lorsqu''il mûrit. Les fruits ne continuent pas à mûrir une fois cueillis.\r\nLe fruit atteint jusqu’à une dizaine de centimètres de diamètre. Il contient de nombreuses graines de la taille d''un grain de maïs, enveloppées d''une pulpe rose grenat, juteuse, sucrée et légèrement acidulée.\r\nLa grenade se consomme presque toujours crue, mais quelques exceptions sont possibles. Étonnez vos invités avec une préparation culinaire à base de ce fruit d''exception !\r\nBien pourvue en vitamine C, la grenade est un fruit de diversification. Elle convient parfaitement aux besoins nutritionnels des femmes, des enfants et des adolescents.', './upload/grenade.jpg', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui'),
(42, 'Groseille', 'Fruit', 1, 'La groseille est le plus souvent d''un beau rouge vif mais elle peut aussi être blanche. Sa chair est moelleuse, juteuse et légèrement acide.\r\nLa groseille est un partenaire original pour vos envies culinaires. Alors osez la créativité et passez le tablier !\r\nNe soyez pas effrayé par sa saveur acidulée et profitez de sa teneur en vitamines et en fibres, d’autant que la petite baie rouge est modérément sucrée.\r\nLa groseille est disponible de juin à septembre.\r\nIl existe une cinquantaine de variétés de groseilliers. Du rouge carmin au blanc, en passant par le violet ou le jaune, la groseille offre une farandole de couleurs.', './upload/groseille.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(43, 'Haricot vert', 'Légume', 2, 'Longue gousse fine, plus ou moins étirée, le haricot vert est classé en 3 catégories : filet, mange-tout et filet mange-tout.\r\nLa production française est principalement située dans l’ouest du pays. En hiver, on importe principalement des haricots verts du Maroc et du Kenya.\r\nCertains haricots verts sont… jaunes : les haricots-beurre !\r\nCuits à l’eau ou à la vapeur, les haricots verts sont délicieux avec des œufs, et accompagnent aussi bien les viandes que les poissons.\r\nIl est riche en minéraux et en vitamines.', './upload/haricotvert.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(44, 'Jujube', 'Fruit', 10, 'La jujube est un fruit ovale ou rond, de couleur jaune, puis rouge-brique à pleine maturité. Il est de taille variable selon les variétés, mais peut atteindre environ 5 cm de longueur. Sa peau est fine et comestible, et sa chair blanche translucide est douce et parfumée. On consomme ce fruit soit frais, soit en confiture ou confit, un peu comme des dattes.\r\nC''est un fruit très nutritif, très riche en vitamine C.', './upload/jujube.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non', 'non'),
(45, 'Kaki', 'Fruit', 275, ' De forme ronde, sa peau est lisse et présente, selon les variétés, une coloration rouge ou orangée. Sa chair est acidulée ou très sucrée.\r\nPlusieurs centaines d’espèces de kaki existent dans le monde. Mais ceux-ci se divisent en deux principaux types : le kaki à chair astringente, de couleur rouge, et le kaki-pomme.\r\nTrès fragile, ce fruit est à consommer dès qu''il est mûr. Alors n''attendez pas et sortez vos petites cuillères ! Ce fruit se prête aussi à plusieurs préparations gastronomiques.\r\nBien pourvu en pigments caroténoïdes au pouvoir antioxydant marqué, ce fruit renferme aussi beaucoup de fibres.', './upload/kaki.jpg', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(46, 'Kiwi', 'Fruit', 100, 'Le kiwi est originaire de Chine. Son nom vient du néo-zélandais « kivi-kivi ». Riche en vitamine C, un seul fruit couvre les apports recommandés pour une journée !\r\nLe Chinabelle® est un kiwi français à la chair jaune. Cette variété est une exclusivité locale. Quant au kiwi de l’Adour, il bénéficie de la certification « Label Rouge ».\r\nRoi du sucré-salé, le kiwi se prête aussi bien aux desserts, qu’aux entrées ou aux plats de résistance.\r\nLe kiwi est un fruit très bien pourvu en vitamine E (1,2 mg/100 g), une vitamine aux vertus anti-oxydantes.', './upload/kiwi.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui'),
(47, 'Kumquat', 'Fruit', 200, 'Le kumquat est le plus petit agrume, il est rond ou ovale, de couleur jaune orangée. C''est un fruit que l''on consomme frais, la peau du kumquat est très fine et comestible, la chair a un goût acidulé de zeste d''agrume et contient de gros pépins. Riche en vitamine C.', './upload/kumquat.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui'),
(48, 'Laitue', 'Légume', 300, 'Avec la mâche et la chicorée, la laitue constitue la troisième grande famille de salade.\r\nPeu calorique, elle vous apporte une grande variété de minéraux et d’oligo-éléments. Également riche en fibres, sa teneur en vitamine C n’est pas négligeable.\r\nEn France, la laitue est le quatrième légume le plus produit, derrière la tomate, la carotte et le chou-fleur. Sa culture se répartit sur l’ensemble du territoire.', './upload/laitue.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(49, 'Lentille', 'Légume', 1, 'Petite graine, la lentille fait partie des légumes secs. Elle est disponible toute l’année.\r\nElle présente des tailles et des couleurs différentes selon les variétés. Plusieurs d’entre-elles sont distinguées et protégées par des labels ou des appellations.\r\nTrès pratique et facile à cuisiner : il suffit de la faire cuire !\r\nLa lentille est très riche en protéines.', './upload/lentille.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui'),
(50, 'Litchi', 'Fruit', 20, ' Sa peau varie du rose clair au rouge foncé. Même dans le noir, impossible de confondre le litchi avec un autre fruit grâce à ses petites écailles et ses arômes de rose et de muscat !\r\nLe litchi se picore en toutes occasions, quotidiennes ou conviviales, mais toujours gourmandes ! Vous pouvez aussi le cuisiner dans de rafraîchissants plats exotiques ou des préparations plus classiques.\r\nExceptionnelle source d''énergie grâce à sa teneur en vitamine C et en glucides, il contient des minéraux et des micronutriments qui participent à votre bien-être.', './upload/litchi.jpg', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui'),
(51, 'Mandarine', 'Fruit', 60, 'La mandarine fait partie de la famille des agrumes, c''est le fruit du mandarinier. C''est un fruit charnu avec une chair orange, juteuse, sucrée et avec des pépins. La peau de la mandarine est fine, d''une couleur orange vif. La mandarine est divisée en plusieurs quartiers environ une dizaine.', './upload/mandarine.jpg', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(52, 'Mangoustan', 'Fruit', 100, ' Mesurant de 4 à 7 cm de diamètre, les fruits sont ronds et un peu aplatis. Leur écorce épaisse est lisse et de couleur vert-jaune. Elle devient pourpre à maturité.\r\nSa coque épaisse cache une savoureuse chair blanche nacrée aux arômes de pêche, d''ananas et de framboise.\r\nA l’intérieur, la chair est divisée en cinq à huit quartiers – les arilles – un peu à la manière d’une clémentine.\r\nRelativement peu utilisé en cuisine, ce fruit exotique trop peu connu est idéal pour surprendre vos invités. Le mangoustan peut être la base de succulents sorbets, mais aussi de bien d’autres préparations.\r\nLe mangoustan est un excellent fruit de diversification. En complément des fruits plus classiques, il contribue à la couverture de nos besoins alimentaires en fibres et en micronutriments.', './upload/mangoustan.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui'),
(53, 'Mangue', 'Fruit', 200, ' Selon les variétés, sa peau peut être jaune, verte ou rouge. La mangue possède une chair onctueuse et parfumée, de couleur jaune-orangé.\r\nOn compte d’innombrables variétés de mangues. Rien qu''en Inde, il en existerait plus d''un millier !\r\nTrès présente dans les desserts, la mangue se marie parfaitement avec les viandes et les poissons : invitez-la à votre table et laissez-vous surprendre !\r\nLa mangue possède une vraie densité en vitamines (provitamine A et vitamine C), en pigments et en acides organiques. Elle apporte également carotène et fibres.', './upload/mangue.jpg', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'oui'),
(54, 'Melon', 'Légume', 600, 'Parmi les différents types commerciaux existants, le melon de type charentais est le plus produit et consommé en France.\r\n• En dépit de son parfum sucré, le melon n’est pas un fruit. Appartenant à la famille des cucurbitacées, comme la courgette ou le potiron, il s’agit d’un légume. Et, avec une saison concentrée sur quelques mois seulement, c’est même le troisième légume le plus consommé des Français !\r\n• Sa chair savoureuse et parfumée se déguste aussi bien nature que cuisinée. Il égaye très simplement une fin de repas ou se mêle à une entrée fraîche et légère.\r\n• Regorgeant de vitamines et de minéraux, le melon présente de nombreux atouts forme. Très riche en eau et peu calorique, il vient à point pour nous désaltérer lors des mois les plus chauds de l’année !', './upload/melon.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(55, 'Mûre', 'Fruit', 2, 'Le goût de la mûre sauvage est très parfumé. En bouche, la mûre de culture a une saveur à la fois douce et acidulée.\r\nSelon les variétés, cette jolie baie est de couleur violet plus ou moins foncé.\r\nCrue ou cuite, elle a beaucoup d''affinités gustatives avec le salé comme avec le sucré.\r\nBien pourvue en vitamines et minéraux, elle présente un apport particulièrement élevé en pigments aux propriétés antioxydantes.\r\nLa mûre est le fruit de la ronce et pousse sur ses lianes épineuses.', './upload/mure.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non'),
(56, 'Myrtille', 'Fruit', 1, 'La chair de la myrtille est juteuse et moelleuse. Son parfum caractéristique ne s''oublie pas de sitôt !\r\nElle a une couleur qui varie du bleu-noir au bleu-violacé. En France, on rencontre deux types de myrtille :\r\nsauvage, elle est alors appelée myrtille noire ou brimbelle ;\r\ncultivée, elle est appelée myrtille arbustive ou bleuet.\r\nGoûtez-la nature et laissez ses saveurs éclater en bouche, ou accommodez-la dans des plats et gâteaux.\r\nPeu calorique, la myrtille est bien pourvue en fibres et en vitamines C, ainsi qu’en minéraux très variés.\r\n', './upload/myrtille.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(57, 'Navet', 'Légume', 300, 'Le navet est une racine, mais saviez-vous qu’il appartient à la famille des choux ?\r\nLégume populaire à travers les siècles, il a l’avantage de pousser sur des sols pauvres. Cela lui a valu d’être pendant longtemps un aliment de base de nombreux plats rustiques.\r\nIl a été très longtemps l’un des aliments de base.\r\nSa douceur est appréciée au printemps. En hiver, son caractère plus marqué entre dans la composition des soupes ou du pot-au-feu.', './upload/navet.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(58, 'Noisette', 'Fruit', 10, 'La noisette, également appelée aveline, se déguste aussi bien sèche que fraîche.\r\nEn France, le noisetier ne fait l''objet d''une production importante que depuis les années 1970. L’Aquitaine en est la principale région productrice.\r\nLes noisettes fraîches sont recherchées pour leur goût subtil ainsi que pour leur texture délicate. Petite mais bien dotée en vitamines, la noisette est gorgée de nutriments bénéfiques.\r\nÉmondées ou non, les noisettes sèches apportent leur croquant à vos préparations culinaires.', './upload/noisette.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non'),
(59, 'Noix', 'Fruit', 15, 'Sa coque, plus ou moins dure, recouvre un fruit à l’amertume légère et à la texture croquante.\r\nD’un apport calorique élevé, la noix regorge d’acides gras essentiels. Elle apporte également fibres et nutriments. Pensez à en croquer une petite poignée pour faire le plein de vitalité.\r\nNature, la noix est délicieuse et croque sous la dent. Cuite ou cuisinée, elle apporte à vos recettes sa saveur légère et délicate.\r\nLa France compte deux grands bassins de production : le Périgord et le Limousin, qui produisent près de 10 variétés différentes.\r\nLa noix est un des fruits de l’automne par excellence.', './upload/noix.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non'),
(60, 'Noix de coco', 'Fruit', 1500, 'Sa coque brune, très dure, contient une chair dense blanc laiteux, la pulpe, très croquante, ainsi qu’un liquide sucré, l’eau de coco.\r\nRiche en acides gras, la noix de coco est un fruit calorique, mais concentré en vitamines, minéraux et oligo-éléments. Croquez sa pulpe pour profiter de ses bienfaits !\r\nLa chair gourmande de la noix de coco est délicieuse nature. Mais vous pouvez aussi donner une touche de gourmandise et d’exotisme à vos plats, de l’entrée au dessert, en utilisant sa pulpe et son eau.', './upload/noixdecoco.jpg', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui'),
(61, 'Oignon', 'Légume', 100, 'Selon les variétés, son poids varie, mais aussi sa forme, bien ronde, allongée ou un peu aplatie et sa couleur, jaune, rouge ou blanc : un véritable chapelet de teintes et d’aspects !\r\nLa production française se concentre surtout dans le nord du pays, même si elle est présente sur quasiment tous ses terroirs. Seuls 2 oignons cultivés sur 10 sont des oignons primeurs.  \r\nIngrédient principal ou exhausteur de goûts, l’oignon est omniprésent dans nos cuisines, toujours à portée de main.\r\nD’un faible apport calorique, les qualités nutritionnelles de ce légume sont reconnues. Riche en vitamines, en minéraux, en oligo-éléments ainsi qu’en fibres, il est source de bien-être et d’équilibre.', './upload/oignon.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(62, 'Olive', 'Fruit', 4, 'L''olive est une drupe ovoïde et globuleuse, de taille variable, de quelques grammes. A maturité, selon les variétés, l''olive est de couleur plus ou moins foncée. L''olive contient un noyau très dûr.\r\nLes olives sont généralement récoltées à pleine maturité, en milieu d''automne, lorsqu''elles commencent à se rider. \r\nCes fruits rentrent dans la fabrication de l''huile d''olive, ou peuvent être préparées en saumures, ou encore accompagner divers plats salés.\r\nL''olive est un fruit très riche en lipides (jusqu''à 99% de l''huile que l''on extrait), mais également en vitamine E et A, ainsi qu''en acides gras, mono et polyinsaturés.', './upload/olive.jpg', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(63, 'Orange', 'Fruit', 200, 'Sa chair goûteuse et gorgée de jus d’un orangé léger se cache sous une peau épaisse et brillante d’un orangé plus soutenu tirant sur le rouge.\r\nAvec la pomme et la banane, l’orange fait partie des fruits les plus consommés en France. On trouve sur les étals les oranges à chair, à jus, ainsi que les oranges sanguines.\r\nQu’on la croque, qu’on la presse ou qu’on la zeste, l’orange est un fruit de base en cuisine. Elle accompagne aussi bien les viandes et les poissons que les légumes ou les pâtisseries.\r\nBon marché, l’orange est disponible tout l’hiver. Gorgée en vitamine C, elle est idéale pour couvrir les besoins quotidiens !\r\nL’orange, pauvre en calories, apporte une quantité importante de minéraux (calcium, magnésium) indispensables au bon équilibre de l’organisme.', './upload/orange.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui'),
(64, 'Oseille', 'Légume', 1, 'Herbacée vivace, l’oseille se distingue par sa feuille en forme de fer de lance.\r\nFraîche, acidulée et pétillante, elle fait figure d’originale dans nombre de préparations culinaires.\r\nVéritable concentré de micronutriments, elle est reconnue pour ses bienfaits… même en petite quantité.', './upload/oseille.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non'),
(65, 'Pamplemousse', 'Fruit', 400, 'Le pamplemousse peut mesurer jusqu''à 20cm de diamètre, et pèse facilement plusieurs kg. Le fruit est arrondi, soit applati soit en forme de poire. Il ne faut pas le confondre avec le pomelo, que l''on trouve beaucoup plus fréquemment sur les étals de fruits. Le pamplemousse reste un fruit qui, pour être consommable frais, doit être cultivé en zone tropicale.', './upload/pamplemousse.jpg', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui'),
(66, 'Papaye', 'Fruit', 1450, 'Sa chair, qui oscille du jaune orangé au rouge le plus intense, est littéralement gorgée d’un jus rafraîchissant et parfumé.\r\nLa chair bien sucrée de la papaye est pauvre en calories, mais contient une quantité importante de vitamines et de minéraux. Un fruit qui s’intègre parfaitement dans une alimentation équilibrée.\r\nConsommée le plus souvent nature, la papaye se prépare rapidement. Vous pouvez l’accommoder pour le dessert, mais aussi l’intégrer à vos plats et vos entrées.\r\nLes papayes françaises sont produites dans les territoires d’outre-mer, et plus particulièrement à la Réunion. Les étals sont également approvisionnés par des fruits en provenance du Brésil, de la Côte d’Ivoire et de la Thaïlande.', './upload/papaye.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui');
INSERT INTO `variety` (`idVariety`, `name`, `category`, `averageWeight`, `description`, `picture`, `Janvier`, `Février`, `Mars`, `Avril`, `Mai`, `Juin`, `Juillet`, `Août`, `Septembre`, `Octobre`, `Novembre`, `Décembre`) VALUES
(67, 'Pastèque', 'Fruit', 3500, 'Ce gros fruit sphérique recouvert d’une peau épaisse vert zébré recèle une pulpe d’un rouge profond. Sa chair, légèrement croquante et peu sucrée, est très désaltérante.\r\nLa pastèque est très riche en eau et légère en calories. Ce fruit riche en vitamines est votre atout forme pendant les beaux jours.\r\nCe fruit désaltérant est délicieux croqué nature, taillé en larges quartiers juteux et gourmands. Coupée en dés ou en billes, la pastèque se marie avec d’autres fruits, des crudités, de la menthe… pour des recettes rafraîchissantes.\r\nOriginaire d’Afrique, la pastèque se nourrit littéralement de chaleur ; elle est donc très peu cultivée en France.', './upload/pasteque.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non'),
(68, 'Pêche', 'Fruit', 150, 'Sa peau lisse ou duvetée prend différentes couleurs déclinant les nuances du blanc au jaune, en passant par l’orange ou le rose. Sa chair parfumée est jaune, blanche, ou même rouge.\r\nD’un apport calorique moyen, la pêche renferme de nombreuses vitamines et des antioxydants.\r\nElle s’associe avec bonheur à des mets salés ou sucrés, ou se mange nature. Juteuse et rafraîchissante, la pêche est un fruit estival par excellence !', './upload/peche.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non'),
(69, 'Persil', 'Légume', 1, 'Le persil est une herbe aromatique très parfumée : il suffit de la froisser entre vos doigts pour sentir son parfum caractéristique caresser vos narines. Il exhale une flaveur chaude et herbacée.\r\nD’un beau vert luisant, ses feuilles forment trois lobes étroits. On distingue deux grandes variétés de persil : le plat, plus goûteux, et le frisé, plus décoratif. Une troisième variété, moins connue, se consomme totalement différemment, il s’agit du persil tubéreux.\r\nSimple à intégrer dans une recette, il est probablement l’aromate le plus utilisé en cuisine.\r\nLe persil est un de vos partenaires bien-être privilégié : juste cueilli, il libère de très nombreux nutriments.', './upload/persil.jpg', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'oui', 'non'),
(70, 'Petit pois', 'Légume', 1, 'Vert et croquant, le petit pois a un goût légèrement sucré. Et pourtant, on ne le mange quasiment que dans des préparations salées.\r\nLes nombreuses variétés de petits pois sont réparties en deux catégories : à écosser ou mange-tout.\r\nConnu cuit dans les plats traditionnels, le petit pois se déguste aussi cru comme une gourmandise.\r\nSur le plan nutritionnel, le petit pois est atypique : il est concentré en fibres et en protéines.', './upload/petitpois.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non'),
(71, 'Pistache', 'Fruit', 1, 'La pistache est une amande charnue, de couleur verdâtre et de saveur douce, logée dans une coque s''ouvrant latéralement quand le fruit est mûr.\r\nLa pistache peut être consommée nature, rôtie, salée. On la retrouve dans de nombreux plats, dans les crèmes glacées, les pâtisseries, etc. C''est une amande riche en potassium, en cuivre et en magnésium.', './upload/pistache.jpg', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non'),
(72, 'Poire', 'Fruit', 120, 'Sa peau lisse se décline en teintes allant du vert au jaune. Sa chair fondante et sucrée en fait le cinquième fruit le plus consommé en France.\r\nD’un faible apport calorique, la poire est gorgée de sucres lents, de vitamines et de fibres. En été comme en hiver, profitez de ses bienfaits et appréciez ses différentes variétés !\r\nSavoureuse nature, elle se prête également à de nombreux accompagnements ou préparations aussi bien sucrées que salées.\r\nS’il existe près de 2 000 variétés, la production de poires en France se concentre sur une dizaine d’entre elles, distinguées en poires d’automne-hiver et en poires d’été.\r\nLeur culture est essentiellement localisée dans le sud et dans le centre du pays.', './upload/poire.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui'),
(73, 'Poireau', 'Légume', 150, 'Le poireau est l’un des légumes phare de l’hiver. Il est produit dans de nombreuses régions françaises et se décline en plusieurs variétés.\r\nIl serait né au Moyen-Orient. Légume populaire chez les Égyptiens et les Romains, il ne cesse, au fil des siècles, de faire de nouveaux adeptes.\r\nPeu calorique, le poireau présente de sérieux atouts nutritionnels par sa richesse en fibres, vitamines et minéraux.\r\nCe légume se cuisine généralement cuit, à la vapeur, braisé ou préalablement blanchi à l’eau avant d’être accommodé de diverses manières.\r\nLe poireau appartient à la famille des alliacées, comme l’ailet l’oignon. Il s’agit d’un légume à bulbe. Sa partie enterrée est blanche. Son corps, appelé « fût » est constitué de feuilles qui s’emboîtent.', './upload/poireau.jpg', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(74, 'Poivron', 'Légume', 200, 'Variété de piment doux, le poivron produit de gros fruits, frais et colorés.\r\nLa palette des couleurs va du vert vif au brun foncé, en passant par le jaune d’or ou le vermillon.\r\nLe panel des saveurs s’étend de l’amer-poivré au sucré.', './upload/poivron.jpg', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(75, 'Pomelo', 'Fruit', 400, 'Sa peau jaune, parfois tachetée de rose ou de rouge, dissimule une chair allant du blond au rouge profond, en passant par le rose tendre. Sa pulpe gorgée de jus est plus ou moins sucrée ou acidulée selon les variétés.\r\nPomelo et pamplemousse sont souvent confondus, il s’agit pourtant de deux espèces distinctes ! Alors que le pamplemousse vient d’Asie du Sud-Est, le pomelo est originaire des Caraïbes. Sa peau est plus fine et sa chair plus juteuse que celle de son cousin éloigné.\r\nTrès léger, le pomelo est un concentré de vitamine C. Facile à consommer, pressé ou à la petite cuillère, il s’intègre facilement dans votre alimentation quotidienne. Alors, à vous de jouer et bénéficiez du tonus qu’il procure !\r\nDélicieux nature, le pomelo est aussi savoureux dans tous vos plats. Il relève à merveille les viandes et poissons, remplit d’énergie les salades de crudités et vitamine vos desserts gourmands.\r\nIl existe de multiples variétés de pomelos. Certaines sont cultivées dans le sud de la France et en Corse, profitant de la chaleur du climat pour s’épanouir.', './upload/pomelo.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non'),
(76, 'Pomme', 'Fruit', 150, 'Selon les variétés, sa peau est verte, rouge, bicolore ou tachetée : une véritable farandole de couleurs ! Sa chair est croquante ou farineuse, douce ou acidulée.\r\nParmi les milliers de variétés de pommes existantes, près de cent sont produites en France, dont une trentaine en très grande quantité.\r\nRâpée ou entière, crue ou cuite, poêlée ou au four, la pomme se prête aux cuisines les plus simples comme les plus sophistiquées. Alors laissez-la vous surprendre !\r\nD’un faible apport calorique, la pomme renferme antioxydants et fibres. Fruit adapté à l’alimentation des sportifs, elle participe à l’équilibre digestif et constitue une mine de vitamines et de nutriments bénéfiques.', './upload/pomme.jpg', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(77, 'Pomme de terre', 'Légume', 200, ' La couleur de la peau et de la chair varie du jaune pâle au violet en passant par le rose. Plus ou moins grosse, la pomme de terre possède une pulpe aux textures différentes selon les variétés.\r\nD’un apport calorique modéré, la pomme de terre est très riche en glucides. Elle apporte également des vitamines et des nutriments. C’est une véritable source d’énergie en hiver.\r\nLa pomme de terre se consomme exclusivement cuite. Elle se prête à de nombreuses préparations gourmandes, poêlées, vapeur, en purée, au four ou en potage.\r\nLa France compte plus de 150 espèces classifiées selon la texture de leur chair et leur usage culinaire.', './upload/pommedeterre.jpg', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui'),
(78, 'Potiron', 'Légume', 15000, 'Le potiron est une cucurbitacée à la saveur douce.\r\nIl présente de multiples apparences, avec ses différentes variétés, ses différentes tailles et ses différentes formes.\r\nIl se prépare aussi bien en entrée, qu’en plat principal, et même en dessert.\r\nNe le confondez pas avec la citrouille, plus ronde, plus orange vif, mais surtout bien moins savoureuse : c’est d’ailleurs elle plutôt que le potiron qu’on évide pour Halloween !\r\nIntéressant pour son apport en vitamine A et ses fibres douces, il est peu calorique tout en restant très nourrissant.', './upload/potiron.jpg', 'oui', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui'),
(79, 'Prune', 'Légume', 30, 'Selon les variétés, sa peau est rouge, bleue, jaune, verte… Sa chair est sucrée ou acidulée.\r\nLa prune se croque directement en bouche ou se cuisine en tartes, en flan, en confitures, etc. On le sait moins, mais elle se prête également aux préparations salées.\r\nTrès sucrée et juteuse, la prune est cependant assez peu calorique et très désaltérante. Vous pouvez donc y succomber à toute heure de la journée. Généreuse en vitamines, en minéraux et en fibres, la prune est au service de votre forme et de votre digestion.', './upload/prune.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(80, 'Radis', 'Légume', 10, 'Le radis compte parmi les premiers légumes cultivés par l’homme. Le radis d’aujourd’hui est bien différent de celui consommé par les Égyptiens ou les Romains.\r\nDes différentes variétés, le petit radis coloré est la plus appréciée. Le gros radis noir a ses adeptes, tandis que le radis japonais devient de plus en plus populaire.\r\nAppréciée crue avec un peu de sel, la racine se déguste également légèrement cuite.\r\nFaible en calories, le radis est un des légumes les plus riches en vitamines.', './upload/radis.jpg', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non', 'non', 'non', 'non'),
(81, 'Raisin', 'Fruit', 325, 'Une grappe de raisins pèse entre 150 et 500 grammes, selon la variété. Ses grains peuvent être noirs, rosés ou blancs. Sa saveur, toujours sucrée, s’agrémente de parfums subtils liés aux variétés ainsi qu’aux terroirs.\r\nEn cuisine, c’est bien simple : le raisin peut accompagner tous vos plats : yaourt, salade, fromage, foie gras, viandes, etc. Un seul mot d’ordre : faites-vous plaisir !\r\nLe raisin est un peu plus sucré que la moyenne des fruits. Vous pouvez cependant le consommer sans crainte, même si vous surveillez votre ligne. Bien pourvu en minéraux, en vitamines et en fibres, c’est par ailleurs un excellent allié au quotidien.', './upload/raisin.jpg', 'non', 'non', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'non', 'non'),
(82, 'Tomate', 'Fruit', 130, 'La tomate est arrivée en France au XVIe siècle après sa découverte en Amérique du Sud. Elle était utilisée, à l’origine, comme plante d’ornement dans les jardins.\r\nOn trouve des milliers de variétés de tomates dans le monde. Elles se distinguent par leur forme, leur couleur, leur texture et leur goût. Les plus consommées en France sont les tomates rondes, les tomates cerises et les allongées.\r\nLa tomate, peu calorique, apporte de nombreux nutriments : vitamines (C et E notamment) et minéraux (magnésium et potassium).\r\nEn cuisine, elle se prépare très facilement et entre dans un grand nombre de préparations aussi bien crue que cuite. Elle se décline même jusqu’au dessert !\r\nSi elle se consomme comme un légume, la tomate est un fruit.', './upload/tomate.jpg', 'non', 'non', 'non', 'non', 'oui', 'oui', 'oui', 'oui', 'oui', 'non', 'non', 'non'),
(91, 'Céleripo', 'Fruit', 8, ' Je suis un fruit !', 'upload/celeri.jpg', 'oui', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oui', 'oui', NULL, NULL);

--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `comment`
--
ALTER TABLE `comment`
  ADD CONSTRAINT `fk_Comment_Member1` FOREIGN KEY (`Member_idMember`) REFERENCES `member` (`idMember`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_comment_offer1` FOREIGN KEY (`offer_numOffer`) REFERENCES `offer` (`numOffer`) ON DELETE CASCADE ON UPDATE NO ACTION;

--
-- Contraintes pour la table `mailalert`
--
ALTER TABLE `mailalert`
  ADD CONSTRAINT `fk_mailAlert_Member1` FOREIGN KEY (`Member_idMember`) REFERENCES `member` (`idMember`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `member_select_offer`
--
ALTER TABLE `member_select_offer`
  ADD CONSTRAINT `fk_member_has_offer_offer1` FOREIGN KEY (`offer_numOffer`) REFERENCES `offer` (`numOffer`) ON DELETE CASCADE ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_member_select_offer_Member1` FOREIGN KEY (`Member_idMember`) REFERENCES `member` (`idMember`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `offer`
--
ALTER TABLE `offer`
  ADD CONSTRAINT `fk_offer_Member1` FOREIGN KEY (`Member_idMember`) REFERENCES `member` (`idMember`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_offer_Variety1` FOREIGN KEY (`Variety_idVariety`) REFERENCES `variety` (`idVariety`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `offer_has_panier`
--
ALTER TABLE `offer_has_panier`
  ADD CONSTRAINT `fk_offer_has_panier_Member1` FOREIGN KEY (`Member_idMember`) REFERENCES `member` (`idMember`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_offer_has_panier_offer1` FOREIGN KEY (`offer_numOffer`) REFERENCES `offer` (`numOffer`) ON DELETE CASCADE ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
